version: "3.9"
services:
  aplicion: 
    build: .
    ports:
      - "3000:3000"
    links:
      - base-datos
  base-datos:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=usuario 
      - MONGO_INITDB_ROOT_PASSWORD=password